services:
  script-backup:
    build:
      context: ./Script-Backup
    container_name: script-backup
    volumes:
      - ./Script-Backup:/app
    env_file:
      - .env
    restart: unless-stopped

  script-limpieza:
    build:
      context: ./Script-limpieza
    container_name: script-limpieza
    volumes:
      - ./Script-limpieza:/usr/local/bin
      - /var/log/script-limpieza.log:/var/log/script-limpieza.log
    env_file:
      - .env
    restart: unless-stopped
